### ISSUE TITLE
Layout is not rendered

### ISSUE THREAD

**Issue by gregorvoinov** [raviroshan/assemble-webpack#1]
hi,

i tried your webpack loader for assemble , and i have a issue that the layout file gets not rendered. it generates all the pages with partials but the layout ist missing...

and yes i have a  {{> body}} in my layout file :)

i use node version 8.9.3 and npm 5.6.0

this is my folder structure
![image](https://user-images.githubusercontent.com/9499590/36205251-68b653ea-118e-11e8-80e8-c1fa346033c7.png)

the plugin

    plugins: [
        new assembleWebpack.AttachedPlugin({
            baseLayout: './src/hbs/layouts/default.hbs',
            basePages: ['./src/hbs/pages/**/*.hbs'],
            partialsLayout: ['./src/hbs/partials/**/*.hbs'],
            partialsData: ['./src/data/**/*.json']
        })
    ],

**Comment by raviroshan** [comment]
@gregorvoinov: Can you upload a sample app on github with your current configuration for reference?
Ideally,  you just need to put `{% body %}` in your layout file where you want to inject your pages, and in the pages you can use `{{> component}}`

Also, one major reason for generating HTML without Layout might be missing configuration on Top of about.hbs file


```
---
layout: default
---

<div>
    <h1>About Page</h1>
</div>
```

**Comment by gregorvoinov** [comment]
hi,

yes i tried {% body %} and set the layout, but didn't worked

i created there a repo https://github.com/gregorvoinov/webpack-assemble-demo

**Comment by raviroshan** [comment]
@gregorvoinov : I have raised a pull request to your repo.
https://github.com/gregorvoinov/webpack-assemble-demo/pull/1

Layout configuration is completed. 

Assemble `Built-in-Variables` are not part of context object itself. You can print and validate the available options using `{{debug}}` which will print the complete CONTEXT on terminal and you can opt for the available options like `{{src.dirname}}`

https://github.com/gregorvoinov/webpack-assemble-demo/pull/1/files#diff-3d754434a35d367bf4935bb74a80eb6fR5

**Comment by gregorvoinov** [comment]
thank you so the main problem was this line, 
---
layout: default
---
i have to remove the extension .hbs and the indent, then it works ;)

only one more question how can i get access to the built in var pages? because its not listed when i use {{debug}}

**Comment by raviroshan** [comment]
@gregorvoinov : for me, `{{debug}}` is printing the complete `CONTEXT` object on terminal.
From there I can see what I need to refer.
example:
```
default: {
	src: {
		dirname
		basename
		name
		extname
		extSegments
		path
		ext
	}
}
```
Can you please elaborate on your exact requirement? Do you want to pass some external data ?

**Comment by gregorvoinov** [comment]
At the built in vars http://assemble.io/docs/Built-in-Variables.html there are also collections (scroll down) And with pages you can easily create a list of all pages, which I find very useful.

**Comment by raviroshan** [comment]
@gregorvoinov : I have updated the package with latest version of assemble "0.24.3" with helper support and don't sure why Built-In-variables are not working.

One reason may be these are now outdated - https://github.com/assemble/assemble#faq

![assemble issue](https://user-images.githubusercontent.com/5485092/45667278-2351ed80-bb36-11e8-8660-530eff6c4f62.png)

**Comment by gregorvoinov** [comment]
wow super, thank you for you effort ;)
