### ISSUE TITLE
Watch .hbs files doesn't work

### ISSUE THREAD

**Issue by gregorvoinov** [raviroshan/assemble-webpack#4]
hi,

I want to watch the .hbs files. I installed this [handlebars loader](https://github.com/pcardune/handlebars-loader) and added the handlbars-loader to my webpack.config.js

```
//handlebars-loader
{
    test: /\.hbs$/,
    loader: 'handlebars-loader'
},
//asselmble-loader
{
    test: /\.(hbs)$/,
        use: [
            {
                loader: 'assemble-webpack'
            }
        ]
    }
```

I start the server with npm run dev, but if i save something inside a .hbs file, there is no rebuild... if i change something in a .scss file it works...

any idea what i'm missing? Or do you have a working demo?

**update:** more [detailed](https://stackoverflow.com/questions/50563102/webpack4-watch-handlebar-files-used-with-assemble-io)

**update2:** 
ok found out what i was missing. inside my main.js i have to require all my .hbs files

    require.context("../hbs", true, /^\.\/.*\.hbs$/);

best regards,
gregor

**Comment by rscarpim** [comment]
Hi, it's possible to render .php files instead of .html ?

Thank you
