### ISSUE TITLE
Errors are not showing

### ISSUE THREAD

**Issue by emiljohansson** [raviroshan/assemble-webpack#6]
The loader seem to be suppressing all errors for me. Does the package support any variables to show them?

I was able to get it to print the errors by adding the gulp-plumber package and `.pipe(plumber())` after the `.toStream('pages')` call.

Thanks

**Comment by raviroshan** [comment]
@emiljohansson : Thank you for raising this issue and providing the potential fix.

I have merged [PR #7](https://github.com/raviroshan/assemble-webpack/pull/7) and published the latest version 3.1.0

<img width="780" alt="screen shot 2018-09-11 at 11 54 59 am" src="https://user-images.githubusercontent.com/5485092/45341915-f04dae00-b5b9-11e8-9a03-90f695634da1.png">
